version: '3.3'

services:
  generator:
    image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-4}
    ports:
      - "${PORT_GENERATOR-8081}:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "${PORT_MAILHOG-8082}:8025"
  proxy:
    image: nginx
    ports:
      - "${PORT_GENERATOR-8080}:80"
    configs:
      - source: site.conf
        target: /etc/nginx/conf.d/default.conf

configs:
  site.conf:
    file: ./site.conf
